apiVersion: v1
kind: Secret
metadata:
  name: repo-gitea-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: http://gitea-http.evidra-demo-gitops.svc.cluster.local:3000/evidra-demo/demo-app.git
  username: evidra-demo
  password: demo-admin-password
  insecure: "true"
