apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin
  namespace: evidra-demo-gitops
type: Opaque
stringData:
  GITEA_ADMIN_USERNAME: evidra-demo
  GITEA_ADMIN_PASSWORD: demo-admin-password
  GITEA_ADMIN_EMAIL: demo@evidra.local
