apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  namespace: evidra-demo-gitops
  labels:
    app.kubernetes.io/name: gitea
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gitea
  ports:
    - name: http
      port: 3000
      targetPort: http
