apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

labels:
  - pairs:
      app.kubernetes.io/environment: prod

secretGenerator:
  - name: evidra-secrets
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      kind: Deployment
      name: evidra
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: ConfigMap
      name: evidra-config
    patch: |-
      - op: replace
        path: /data/EVIDRA_ARGO_COLLECTOR_ENABLED
        value: "true"
      - op: replace
        path: /data/EVIDRA_ARGO_DEFAULT_ENV
        value: "prod"
      - op: add
        path: /data/EVIDRA_DEV_INSECURE
        value: "false"
      - op: add
        path: /data/EVIDRA_AUTH_RATE_LIMIT_ENABLED
        value: "true"
      - op: add
        path: /data/EVIDRA_AUTH_RATE_LIMIT_READ_PER_MIN
        value: "600"
      - op: add
        path: /data/EVIDRA_AUTH_RATE_LIMIT_EXPORT_PER_MIN
        value: "120"
      - op: add
        path: /data/EVIDRA_AUTH_RATE_LIMIT_INGEST_PER_MIN
        value: "240"

images:
  - name: evidra
    newName: evidra
    newTag: prod
